version: '3'

services:
  camunda-duty-calculator:
    container_name: camunda-duty-calculator
    image: cphmn492/camunda-duty-calculator
    networks: 
      - cam
    depends_on:
      - camunda
  camunda-price-converter-rmiclient:
    container_name: camunda-price-converter-rmiclient
    image: cphmn492/camunda-price-converter-rmiclient
    networks: 
      - cam
    depends_on:
      - camunda
      - price-converter-rmiserver
  price-converter-rmiserver:
    container_name: price-converter-rmiserver
    image: cphmn492/price-converter-rmiserver
    expose:
      - "1099"
    networks: 
      - cam
  camunda-car-rest-service-client:
    container_name: camunda-car-rest-service-client
    image: cphmn492/camunda-car-rest-service-client
    networks: 
      - cam
    depends_on:
      - camunda
      - car-rest-service
  car-rest-service:
    container_name: car-rest-service
    image: cphmn492/car-rest-service
    ports:
      - "8090:8090"
    networks: 
      - cam
  scraper-monolith:
    container_name: scraper-monolith
    image: cphmn492/scraper-monolith
    networks: 
      - cam
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:${DISTRO:-latest}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks: 
      - cam

networks:
  cam:
    driver: "bridge"