version: '3.7'

services:
  camunda: # service name
    image: camunda/camunda-bpm-platform:${DISTRO:-latest}
    ports:
      - "8082:8080"
    expose:
      - "8082"
    restart: "on-failure" # restart camunda container if it fails
  camunda-duty-calculator:
    image: cphmn492/camunda-duty-calculator
    restart: "on-failure"
    depends_on:
      - camunda # camunda-duty-calculator will only start if camunda is up and running
  price-converter-rmiserver:
    image: cphmn492/price-converter-rmiserver
    restart: "on-failure"
  camunda-price-converter-rmiclient:
    image: cphmn492/camunda-price-converter-rmiclient
    restart: "on-failure"
    depends_on:
      - camunda # camunda-duty-calculator will only start if camunda is up and running
  camunda-car-rest-service-client:
    image: cphmn492/camunda-car-rest-service-client
    restart: "on-failure"
    depends_on:
      - camunda # camunda-duty-calculator will only start if camunda is up and running
      - car-rest-service
  car-rest-service:
    image: cphmn492/car-rest-service
    ports: # host:container- Bind the container port(8080) to the host port(8082) Any traffic from the host via port 8082 will go to the docker container via port 8080 
      - "8090:8090"
    expose:
      - "8090"
    restart: "on-failure"
  scraper-monolith:
    image: cphmn492/scraper-monolith
    restart: "on-failure"